services:
  # PHP-FPM (App)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: hkc-app
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - hkc-network
    depends_on:
      - mysql
      - redis
    ports:
      - "5173:5173"

  # Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: hkc-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hkc-network
    depends_on:
      - app

  # Database
  mysql:
    image: mysql:8.0
    container_name: hkc-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - hkc-network
    ports:
      - "3306:3306"

  # Redis
  redis:
    image: redis:alpine
    container_name: hkc-redis
    volumes:
      - redis-data:/data
    networks:
      - hkc-network

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hkc-pma
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - hkc-network
    depends_on:
      - mysql

networks:
  hkc-network:
    driver: bridge

volumes:
  db-data:
  redis-data: